# Generated by Django 3.2.4 on 2021-07-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_myuser_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='full_name',
        ),
    ]
